name: ridare
channels:
  - conda-forge
  - defaults
dependencies:
  - backports.zstd=1.3.0
  - blinker=1.9.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - daiquiri=3.0.0
  - docopt=0.6.2
  - exceptiongroup=1.3.1
  - filelock=3.20.3
  - flask=3.1.2
  - flask_cors=4.0.0
  - grip=4.6.2
  - gunicorn=23.0.0
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - importlib-metadata=8.7.0
  - iniconfig=2.3.0
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - libcxx=21.1.8
  - libexpat=2.7.3
  - libffi=3.5.2
  - libiconv=1.18
  - liblzma=5.8.2
  - libmpdec=4.0.0
  - libsqlite=3.51.2
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lxml=6.0.2
  - markdown=3.10.1
  - markupsafe=3.0.3
  - ncurses=6.5
  - openssl=3.6.0
  - packaging=26.0
  - path-and-address=2.0.1
  - pip=25.3
  - pluggy=1.6.0
  - pygments=2.19.2
  - pysocks=1.7.1
  - pytest=9.0.2
  - pytest-flask=1.3.0
  - python=3.14.2
  - python-json-logger=2.0.7
  - python_abi=3.14
  - readline=8.3
  - requests=2.32.5
  - setuptools=80.10.1
  - six=1.17.0
  - tk=8.6.13
  - tomli=2.4.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.3
  - werkzeug=3.1.5
  - zipp=3.23.0
  - zstd=1.5.7
prefix: /opt/miniconda3/envs/ridare
