name: ridare
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blinker=1.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - click=8.2.1
  - colorama=0.4.6
  - daiquiri=3.0.0
  - docopt=0.6.2
  - exceptiongroup=1.3.0
  - filelock=3.19.1
  - flask=3.1.2
  - grip=4.6.2
  - gunicorn=23.0.0
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.7.0
  - iniconfig=2.0.0
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - ld_impl_linux-64=2.44
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - libiconv=1.18
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.50.4
  - libstdcxx=15.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lxml=6.0.1
  - markdown=3.8.2
  - markupsafe=3.0.2
  - ncurses=6.5
  - openssl=3.5.2
  - packaging=25.0
  - path-and-address=2.0.1
  - pip=25.2
  - pluggy=1.6.0
  - pycparser=2.22
  - pygments=2.19.2
  - pysocks=1.7.1
  - pytest=8.4.1
  - python=3.11.13
  - python-json-logger=2.0.7
  - python_abi=3.11
  - readline=8.2
  - requests=2.32.5
  - setuptools=80.9.0
  - tk=8.6.13
  - tomli=2.2.1
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - zipp=3.23.0
  - zstandard=0.24.0
  - zstd=1.5.7
prefix: /home/servilla/miniconda3/envs/ridare
