name: ridare
channels:
  - conda-forge
  - defaults
dependencies:
  - markdown
  - flask
  - pip
  - lxml
  - pytest
  - pytest-flask
  - daiquiri
  - filelock
  - gunicorn
  - jinja2
  - requests
  - grip
  - libiconv
  - flask-cors
prefix: /opt/miniconda3/envs/ridare
