name: ridare
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blinker=1.9.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - daiquiri=3.0.0
  - docopt=0.6.2
  - exceptiongroup=1.3.1
  - filelock=3.20.0
  - flask=3.1.2
  - grip=4.6.2
  - gunicorn=23.0.0
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - iniconfig=2.3.0
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - ld_impl_linux-64=2.45
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.51.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lxml=6.0.2
  - markdown=3.10
  - markupsafe=3.0.3
  - ncurses=6.5
  - openssl=3.6.0
  - packaging=25.0
  - path-and-address=2.0.1
  - pip=25.3
  - pluggy=1.6.0
  - pycparser=2.22
  - pygments=2.19.2
  - pysocks=1.7.1
  - pytest=9.0.1
  - pytest-flask=1.3.0
  - python=3.11.14
  - python-json-logger=2.0.7
  - python_abi=3.11
  - readline=8.2
  - requests=2.32.5
  - setuptools=80.9.0
  - tk=8.6.13
  - tomli=2.3.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - zipp=3.23.0
  - zstandard=0.25.0
  - zstd=1.5.7
prefix: /home/pasta/miniconda3/envs/ridare
