name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=1.0.0
  - archspec=0.2.5
  - babel=2.17.0
  - boltons=24.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - certifi=2026.01.04
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - colorama=0.4.6
  - conda=25.11.1
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.4.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - cpp-expected=1.1.0
  - cryptography=44.0.3
  - defusedxml=0.7.1
  - distro=1.9.0
  - docutils=0.21.2
  - fmt=11.1.4
  - frozendict=2.4.6
  - h2=4.2.0
  - hpack=4.1.0
  - httpie=3.2.4
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagesize=1.4.1
  - importlib-metadata=8.6.1
  - jinja2=3.1.6
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libarchive=3.7.7
  - libcurl=8.13.0
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - libiconv=1.18
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmamba=2.1.1
  - libmambapy=2.1.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libsolv=0.7.32
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - menuinst=2.2.0
  - multidict=6.4.3
  - ncurses=6.5
  - nlohmann_json=3.11.3
  - openssl=3.6.0
  - packaging=25.0
  - pip=25.1.1
  - platformdirs=4.3.8
  - pluggy=1.6.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.10.14
  - python_abi=3.10
  - pytz=2025.2
  - readline=8.2
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.3
  - requests-toolbelt=1.0.0
  - rich=14.0.0
  - ripgrep=14.1.1
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.8
  - setuptools=80.1.0
  - simdjson=3.12.3
  - six=1.17.0
  - snowballstemmer=2.2.0
  - sphinx=8.1.3
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - tk=8.6.13
  - tomli=2.2.1
  - tqdm=4.67.1
  - truststore=0.10.1
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - tzdata=2025b
  - urllib3=2.4.0
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml-cpp=0.8.0
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - flake8==7.1.2
      - mccabe==0.7.0
      - pycodestyle==2.12.1
      - pyflakes==3.2.0
prefix: /home/pasta/miniconda3
